#%RAML 1.0
title: getProducts
baseUri: https://localhost:8081/products
/products:
  get:
    description: get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productId":"123456",
                "productName":"Apple",
                "productDesc":"food product"
              }
